### ISSUE TITLE
Swift : misplaced documentation for `subscript`

### ISSUE THREAD

**Issue by groue** [realm/jazzy#250]
Hello,

In the http://cocoadocs.org/docsets/GRMustache.swift/0.9.2/Classes/Context.html page, the documentation for `subscript(_:)` is placed in the "Creating Contexts" section, whereas it should appear under the "Fetching Values from the Context Stack" section, since the declaration of the subscript function is located below the `// MARK: - Fetching Values from the Context Stack comment.`

It looks that this bug is specific to subscript functions.

(Originally posted on https://github.com/CocoaPods/cocoadocs.org/issues/352)

**Comment by jpsim** [comment]
I also think this will be addressed by https://github.com/jpsim/SourceKitten/pull/104.

**Comment by groue** [comment]
Thanks again!

**Comment by jpsim** [comment]
@groue comparing the docs from [0.9.2](http://cocoadocs.org/docsets/GRMustache.swift/0.9.2/Classes/Context.html) vs [1.0.1](http://cocoadocs.org/docsets/GRMustache.swift/1.0.1/Classes/Context.html), it appears `subscript(_:)` was removed. Looking at the source too ([Context.swift](https://github.com/groue/GRMustache.swift/blob/1.0.1/Sources/Context.swift)). So it's hard for me to confirm that this is indeed fixed. Could you confirm this for me if you get the chance? Thanks!

**Comment by groue** [comment]
Hello @jpsim. I can't confirm with GRMustache.

But with [GRDB](http://github.com/groue/GRDB.swift), the subscript defined at [Row.swift#L606](https://github.com/groue/GRDB.swift/blob/v0.72.0/GRDB/Core/Row.swift#L606) is not visible at all in [0.72.0 documentation](http://cocoadocs.org/docsets/GRDB.swift/0.72.0/Classes/Row.html).

**Comment by jpsim** [comment]
Thanks for sharing that. I'm very confused as to why that's happening, even reproducing it locally isn't helping me understand why `subscript(_:)` is sometimes being skipped, sometimes not. I'll take another look again some other time hoping my mind is clearer.

**Comment by johnfairh** [comment]
Latest jazzy 0.8.2 made some fixes about honouring the position of 'subscript', good chance this is fixed now.  I build the docs from GRDB 0.107.0 & Row.swift has its subscript showing in the correct position.

**Comment by jpsim** [comment]
I'll optimistically close this hoping that 0.8.2 has indeed addressed the problems surfaced here, but please comment either way, if fixed or still broken. Thanks!

**Comment by groue** [comment]
Fix confirmed. Thanks @jpsim and @johnfairh !
