### ISSUE TITLE
Deduplicate podspec declarations

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#439]
When concatenating sourcekitten runs for different podspec targets, we end up with multiple versions of the same declaration: https://github.com/realm/jazzy-integration-specs/blob/jp-deprecate-swift-1/document_moya_podspec/after/execution_output.txt#L24

This causes incorrect warnings to be displayed, and makes the list of undocumented tokens explode in size due to all the duplicates: https://github.com/realm/jazzy-integration-specs/blob/jp-deprecate-swift-1/document_moya_podspec/after/docs/undocumented.txt

**Comment by AliSoftware** [comment]
`jazzy` seem to fail while parsing the documentation for my pod [`Reusable`](https://github.com/AliSoftware/Reusable) locally when telling it to [use the podspec](https://github.com/AliSoftware/Reusable/blob/master/Reusable.podspec), because it seems to run `xcodebuild` twice and then finds duplicates for all the declarations.

I'm guessing that's the same issue as you described here? If so, don't hesitate if you need me to test stuff on my pod to help investigate.

```sh
$ jazzy --version
jazzy version: 0.5.0

$ pod --version
0.39.0

$ jazzy --podspec Reusable.podspec                                                                                                                             01:23:43 
Updating local specs repositories

CocoaPods 1.0.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `Reusable` from `/Users/olivier/Documents/Dev/GitHub/AliSoftware/Reusable`
Downloading dependencies
Installing Reusable (2.1.0)
Generating Pods project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
Running xcodebuild
Parsing NibLoadable.swift (1/2)
Parsing Reusable.swift (2/2)
Running xcodebuild
Parsing NibLoadable.swift (1/2)
Parsing Reusable.swift (2/2)
building site
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: protocol NibLoadable, protocol NibLoadable
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: static variable nib, static variable nib
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: static method loadFromNib(), static method loadFromNib()
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: protocol Reusable, protocol Reusable
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: static variable reuseIdentifier, static variable reuseIdentifier
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: protocol NibReusable, protocol NibReusable
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method registerReusableCell(_:), instance method registerReusableCell(_:)
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method registerReusableCell(_:), instance method registerReusableCell(_:)
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method dequeueReusableCell(indexPath:), instance method dequeueReusableCell(indexPath:)
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method registerReusableHeaderFooterView(_:), instance method registerReusableHeaderFooterView(_:)
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method registerReusableHeaderFooterView(_:), instance method registerReusableHeaderFooterView(_:)
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method dequeueReusableHeaderFooterView(), instance method dequeueReusableHeaderFooterView()
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method registerReusableCell(_:), instance method registerReusableCell(_:)
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method registerReusableCell(_:), instance method registerReusableCell(_:)
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method dequeueReusableCell(indexPath:), instance method dequeueReusableCell(indexPath:)
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method registerReusableSupplementaryView(_:viewType:), instance method registerReusableSupplementaryView(_:viewType:)
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method registerReusableSupplementaryView(_:viewType:), instance method registerReusableSupplementaryView(_:viewType:)
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method dequeueReusableSupplementaryView(_:indexPath:), instance method dequeueReusableSupplementaryView(_:indexPath:)
jam out ♪♫ to your fresh new docs in `docs`
```

**Comment by negebauer** [comment]
I'm having the same issue with my pod
I found that this piece of the `podspec` triggers the run of `xcodebuild`  multiple times
```ruby
s.ios.deployment_target = '9.0'
s.osx.deployment_target = '10.11'
s.watchos.deployment_target = '2.0'
s.tvos.deployment_target = '9.0'
```
If I change it to this
```ruby
s.ios.deployment_target = '9.0'
# s.osx.deployment_target = '10.11'
# s.watchos.deployment_target = '2.0'
# s.tvos.deployment_target = '9.0'
```
`xcodebuild` runs only one time and the warnings aren't generated

**Comment by istx25** [comment]
Seems to me that this has been resolved. Closing for now. Feel free to re-open if necessary.

**Comment by jpsim** [comment]
Nope. Jazzy will still generate duplicate symbols. That's expected, and mostly harmless other than the logged warning, but still not ideal.

**Comment by istx25** [comment]
Thanks for clarifying.

**Comment by gwangpa** [comment]
Hi, any chance to resolve this issue. I'm having same issue with version `0.12.0`.

**Comment by johnfairh** [comment]
@gwangpa as a user you can ignore the warning; if you want to write a PR I can point you in the right direction?

**Comment by johnfairh** [comment]
Closing as no-fix-planned - given the lifecycle of both Jazzy and CocoaPods.
